### ISSUE TITLE
Calling function back and forth between javascript and C#

### ISSUE THREAD

**Issue by ThibaudMZN** [michael-russin/webview2-control#11]
Formerly, when using the basic C# WebBrowser, I was able to call a C# function from a JS file using the window.external calling. The other way around was also possible using Document.InvokeScript(args).

Is there any way to achieve that using your current implementation ?

**Comment by michael-russin** [comment]
You can use web messages to send JSON back and forth between Javascript and C#.  In the sample there is some examples that use WebMessageRecieved event to receive messages and  PostWebMessageAsJson to send them to Javascript.   Or you can use an ActiveX object and AddRemoteObject/RemoveRemoteObject methods similar to what the IE WebBrowser control has.

**Comment by ThibaudMZN** [comment]
Thanks, I'm gonna take a look at that it should do the trick !
