### ISSUE TITLE
Is this specifically blocked when running against release version of edge?

### ISSUE THREAD

**Issue by cenright** [michael-russin/webview2-control#15]
I am using 0.9.430.3 which claims it needs:

minimum Microsoft Edge version 82.0.430.0.

The latest release Edge version for me:
Version 83.0.4103.106 (Official Build) (64-bit)

I get:
Failed to create webview environment 80070002

seems to work fine on my machine with the latest canary installed.

**Comment by michael-russin** [comment]
It doesn't but the underlying WebView2 has had some issues recently.  I think this is the same issue you are seeing.  https://github.com/MicrosoftEdge/WebViewFeedback/issues/203

**Comment by cenright** [comment]
Thank you for the update.
