### ISSUE TITLE
Can I built against the ".NETFramework,Version=v4.5." framework?

### ISSUE THREAD

**Issue by wentong-wow** [michael-russin/webview2-control#8]
Hi,

From nuget, the dependency .NETFramework version is 4.5. But build output tell us target need to use .NETFramework Version=v4.6.1. Can I re-build source code as .NETFramework version is 4.5? 

Thanks

BR,
WenTong Liu

**Comment by michael-russin** [comment]
I changed the target version of the assembly and uploaded a new nuget package.  It should work with 4.5 now.

**Comment by wentong-wow** [comment]
Thanks a lot.
